version: "3"
services:
  burger-builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /burgerbuilder/node_modules
      - .:/burgerbuilder
